### ISSUE TITLE
Error with 

### ISSUE THREAD

**Issue by ando2097** [ARM-software/ML-examples#64]
## issue
attempting to run the cmsisnn-cifar10 ML-example

## command typed

python3 nn_quantizer.py --model models/cifar10_m4_train_test.prototxt --weights models/cifar10_m4_iter_70000.caffemodel.h5 --save models/cifar10_m4.pkl 

## error message

I0804 16:46:04.856118 22909 net.cpp:257] Network initialization done.
I0804 16:46:04.871187 22909 net.cpp:801] Ignoring source layer cifar
I0804 16:46:04.871275 22909 hdf5.cpp:33] Datatype class: H5T_FLOAT
Traceback (most recent call last):
  File "nn_quantizer.py", line 614, in <module>
    my_model.get_graph_connectivity()
  File "nn_quantizer.py", line 234, in get_graph_connectivity
    for key, value in self.top_blob.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by Burton2000** [comment]
Hi there,

Think this is an issue with Python2 vs Python3. Python3 changed iteritems() to items() and unfortunately we have not updated this example yet. To fix it either use Python2 or replace iteritems() to items() in the code.

We have a plan to clean up the examples in this repository, so this will be on our radar to fix as well.
